### ISSUE TITLE
Incorrect template is displayed when pressing 'add new'

### ISSUE THREAD

**Issue by xferra** [repometric/hub.repometric.com#4]
URL in form action contains `?` char, which an incorrect way of passing arguments to form; as a result, the generic template is used for new issue instead of 'Add new engine'.

[Here](https://stackoverflow.com/a/1977439) are the explanation and example.

**Comment by svoboda-rabsvto** [comment]
I think it's worth using <a> with href attribute or <button> with javascript , also this button need in styling :)

**Comment by dnovikau** [comment]
fixed by commit https://github.com/repometric/hub.repometric.com/commit/58ac3df455bccc39fea0b14b93ebdcc69dc52501
